// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10pLiV5uk6K3O1LtAmiOXVxIKDZ6MD7M',
    appId: '1:901674071868:web:715c892c86f1dd287a1039',
    messagingSenderId: '901674071868',
    projectId: 'hundredheadssociety',
    authDomain: 'hundredheadssociety.firebaseapp.com',
    storageBucket: 'hundredheadssociety.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10pLiV5uk6K3O1LtAmiOXVxIKDZ6MD7M',
    appId: '1:901674071868:android:caccfeebb722027f7a1039',
    messagingSenderId: '901674071868',
    projectId: 'hundredheadssociety',
    storageBucket: 'hundredheadssociety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10pLiV5uk6K3O1LtAmiOXVxIKDZ6MD7M',
    appId: '1:901674071868:ios:d71dcb8dea79182c7a1039',
    messagingSenderId: '901674071868',
    projectId: 'hundredheadssociety',
    storageBucket: 'hundredheadssociety.firebasestorage.app',
    iosBundleId: 'com.hundredheadsociety.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10pLiV5uk6K3O1LtAmiOXVxIKDZ6MD7M',
    appId: '1:901674071868:macos:caccfeebb722027f7a1039',
    messagingSenderId: '901674071868',
    projectId: 'hundredheadssociety',
    storageBucket: 'hundredheadssociety.firebasestorage.app',
    iosBundleId: 'com.hundredheadsociety.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA10pLiV5uk6K3O1LtAmiOXVxIKDZ6MD7M',
    appId: '1:901674071868:windows:caccfeebb722027f7a1039',
    messagingSenderId: '901674071868',
    projectId: 'hundredheadssociety',
    storageBucket: 'hundredheadssociety.firebasestorage.app',
  );
} 